/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 10
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 13
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_DASH = 1,
  anon_sym_C = 2,
  anon_sym_D = 3,
  anon_sym_E = 4,
  anon_sym_F = 5,
  anon_sym_G = 6,
  anon_sym_A = 7,
  anon_sym_B = 8,
  sym_source_file = 9,
  sym_note_sequence = 10,
  sym_note = 11,
  aux_sym_note_sequence_repeat1 = 12,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DASH] = "-",
  [anon_sym_C] = "C",
  [anon_sym_D] = "D",
  [anon_sym_E] = "E",
  [anon_sym_F] = "F",
  [anon_sym_G] = "G",
  [anon_sym_A] = "A",
  [anon_sym_B] = "B",
  [sym_source_file] = "source_file",
  [sym_note_sequence] = "note_sequence",
  [sym_note] = "note",
  [aux_sym_note_sequence_repeat1] = "note_sequence_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_C] = anon_sym_C,
  [anon_sym_D] = anon_sym_D,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_F] = anon_sym_F,
  [anon_sym_G] = anon_sym_G,
  [anon_sym_A] = anon_sym_A,
  [anon_sym_B] = anon_sym_B,
  [sym_source_file] = sym_source_file,
  [sym_note_sequence] = sym_note_sequence,
  [sym_note] = sym_note,
  [aux_sym_note_sequence_repeat1] = aux_sym_note_sequence_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_C] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_D] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_G] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_A] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_B] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_note_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_note_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      ADVANCE_MAP(
        '-', 2,
        'A', 8,
        'B', 9,
        'C', 3,
        'D', 4,
        'E', 5,
        'F', 6,
        'G', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_C);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_D);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_F);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_G);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_A);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_B);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_C] = ACTIONS(1),
    [anon_sym_D] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_F] = ACTIONS(1),
    [anon_sym_G] = ACTIONS(1),
    [anon_sym_A] = ACTIONS(1),
    [anon_sym_B] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(8),
    [sym_note_sequence] = STATE(9),
    [sym_note] = STATE(3),
    [anon_sym_C] = ACTIONS(3),
    [anon_sym_D] = ACTIONS(3),
    [anon_sym_E] = ACTIONS(3),
    [anon_sym_F] = ACTIONS(3),
    [anon_sym_G] = ACTIONS(3),
    [anon_sym_A] = ACTIONS(3),
    [anon_sym_B] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_note] = STATE(7),
    [anon_sym_C] = ACTIONS(3),
    [anon_sym_D] = ACTIONS(3),
    [anon_sym_E] = ACTIONS(3),
    [anon_sym_F] = ACTIONS(3),
    [anon_sym_G] = ACTIONS(3),
    [anon_sym_A] = ACTIONS(3),
    [anon_sym_B] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      anon_sym_DASH,
    STATE(4), 1,
      aux_sym_note_sequence_repeat1,
  [10] = 3,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym_note_sequence_repeat1,
  [20] = 3,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_DASH,
    STATE(5), 1,
      aux_sym_note_sequence_repeat1,
  [30] = 1,
    ACTIONS(16), 2,
      ts_builtin_sym_end,
      anon_sym_DASH,
  [35] = 1,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      anon_sym_DASH,
  [40] = 1,
    ACTIONS(18), 1,
      ts_builtin_sym_end,
  [44] = 1,
    ACTIONS(20), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 10,
  [SMALL_STATE(5)] = 20,
  [SMALL_STATE(6)] = 30,
  [SMALL_STATE(7)] = 35,
  [SMALL_STATE(8)] = 40,
  [SMALL_STATE(9)] = 44,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_sequence, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_sequence, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 1, 0, 0),
  [18] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_musical_notes(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
